[build]
builder = "NIXPACKS"
nixpacksPlan = "{\"phases\":{\"setup\":{\"nixPkgs\":[\"nodejs_20\",\"libreoffice-bin\",\"liberation_ttf\"]}}}"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
